[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
code-timing-macros = { version = "0.0.6", features = ["tracing"] }
const_format = "0.2.35"

# Additional recommended dependencies
itertools = "0.14.0"
regex = "1.12.2"

[features]
tracing = []